name: Deploy to Linux Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
        shell: bash

      - name: Connect and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" << 'EOF'
            sudo mkdir -p /var/www/myproject
            sudo chown -R "${{ secrets.SSH_USER }}":"${{ secrets.SSH_USER }}" /var/www/myproject
      
            if [ ! -d '/var/www/myproject/.git' ]; then 
              sudo -u "${{ secrets.SSH_USER }}" git clone git@github.com:https://github.com/ArulrajGopal/english_dict.git /var/www/myproject
            else 
              cd /var/www/myproject && sudo -u "${{ secrets.SSH_USER }}" git pull origin main
            fi
      
            sudo rsync -av --exclude='.git' /var/www/myproject/static /var/www/html/
          EOF




